[package]
name = "facebook-stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
plotters = "0.3.4"
serde = {version = "1.0.162", features = ["derive"]}
serde_json = "1.0.96"
